### PR TITLE
Add /frontend/init as an api endpoint

### PR DESCRIPTION
**Pull request by jlipinski3**

### CODE REVIEW

**Comment by jlipinski3** [comment]
@tfhartmann I need some help testing. This is solely for dev at the moment. It's a new feature - we have three /init endpoints including this right now. These will be consolidated and we're ultimately looking to host these endpoints at the root, which is something we'll be looking to do soon (within the next few wks). As of right now though I need the /frontend/init endpoint for continued dev.

**Comment by tfhartmann** [comment]
Cool,

We should probably get https://github.com/asicsdigital/terraform-aid/blob/master/env-development/main.tf#L21 <https://github.com/asicsdigital/terraform-aid/blob/master/env-development/main.tf#L21> updated to point to your branch, and merge that into the dev-release branch so you won’t get overwritten when you folks deploy to dev! You may want to give Judson a moment, he’s got a pending rebased PR that he’s trying to get into master as well

**Comment by jadunawa** [comment]
@tfhartmann do I need to get my PR fully merged or just push conflict resolved before @jlipinski3 can move forward?

**Comment by jlipinski3** [comment]
@noss @tfhartmann is this ok to merge?

**Comment by noss** [comment]
I redirect the review request to @jnoss instead.

**Pull request merged**
